In [1]:
import numpy as np


In [3]:
A = np.array([[56.0,0.0,4.4,68.0],[1.2,104.0,52.0,8.0],[1.8,135.0,99.0,0.9]])

In [4]:
A

array([[  56. ,    0. ,    4.4,   68. ],
       [   1.2,  104. ,   52. ,    8. ],
       [   1.8,  135. ,   99. ,    0.9]])

In [15]:
cal = A.sum(axis=0)
test = cal.reshape(1,4)
test

array([[  59. ,  239. ,  155.4,   76.9]])

In [12]:
percentage = 100*A/cal.reshape(1,4)
percentage

array([[ 94.91525424,   0.        ,   2.83140283,  88.42652796],
       [  2.03389831,  43.51464435,  33.46203346,  10.40312094],
       [  3.05084746,  56.48535565,  63.70656371,   1.17035111]])

In [21]:
a = np.random.randn(5,1)

In [22]:
a

array([[ 0.25186832],
       [ 0.6554405 ],
       [ 0.9706325 ],
       [ 1.22540248],
       [-1.56730809]])

In [23]:
a.shape

(5, 1)

In [24]:
a.T

array([[ 0.25186832,  0.6554405 ,  0.9706325 ,  1.22540248, -1.56730809]])

In [26]:
np.dot(a, a.T)

array([[ 0.06343765,  0.16508469,  0.24447158,  0.30864006, -0.39475525],
       [ 0.16508469,  0.42960224,  0.63619185,  0.80317841, -1.02727719],
       [ 0.24447158,  0.63619185,  0.94212746,  1.18941547, -1.52128018],
       [ 0.30864006,  0.80317841,  1.18941547,  1.50161123, -1.92058322],
       [-0.39475525, -1.02727719, -1.52128018, -1.92058322,  2.45645466]])

In [27]:
b = np.random.randn(5)
b.shape

(5,)

In [28]:
b = b.reshape((1,5))

In [29]:
b

array([[-0.46458778,  0.51130948,  0.93235424, -0.18585932,  0.60387992]])

In [30]:
b = b.reshape((5,1))

In [31]:
b

array([[-0.46458778],
       [ 0.51130948],
       [ 0.93235424],
       [-0.18585932],
       [ 0.60387992]])

In [32]:
np.exp?

In [35]:

np.ndarray?

In [36]:
image = np.array([[[ 0.67826139,  0.29380381],
        [ 0.90714982,  0.52835647],
        [ 0.4215251 ,  0.45017551]],

       [[ 0.92814219,  0.96677647],
        [ 0.85304703,  0.52351845],
        [ 0.19981397,  0.27417313]],

       [[ 0.60659855,  0.00533165],
        [ 0.10820313,  0.49978937],
        [ 0.34144279,  0.94630077]]])

In [42]:
image.shape[0]

3

In [40]:
image.shape[2]

2

In [41]:
image.reshape(len(image.shape),1)

ValueError: total size of new array must be unchanged

In [43]:
np.array([1, 2, 3])

array([1, 2, 3])

In [44]:
np.array([1, 2, 3]).shape

(3,)

In [45]:
a = np.array([1, 2, 3]).reshape(3,1)

In [46]:
a.shape

(3, 1)

In [47]:
a

array([[1],
       [2],
       [3]])

In [48]:
np.array([[1, 2, 3],[4, 5, 6]]).reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [49]:
a

array([[1],
       [2],
       [3]])

In [50]:
np.zeros(5,1)

TypeError: data type not understood

In [51]:
np.zeros((2,1))

array([[ 0.],
       [ 0.]])

In [52]:
a = np.random.randn(3, 3)

In [53]:
b = np.random.randn(3, 1)

In [54]:
c = a*b

In [55]:
c

array([[ -2.99565087e+00,   1.25912412e-01,  -2.40951532e-01],
       [ -1.07527383e-03,   3.87249072e-02,   1.03360884e-01],
       [ -3.48776971e-01,   4.95435827e-02,   3.24271816e-01]])

In [56]:
c.shape

(3, 3)

In [58]:
a = np.random.randn(2, 3)

In [59]:
b = np.random.randn(2, 1)

In [60]:
c = a + b

In [61]:
c.shape

(2, 3)

In [62]:
a = np.random.randn(4, 3)

In [63]:
b = np.random.randn(3, 2)

In [64]:
c = a*b

ValueError: operands could not be broadcast together with shapes (4,3) (3,2) 

In [65]:
a = np.random.randn(4, 3) # a.shape = (4, 3)
b = np.random.randn(3, 2) # b.shape = (3, 2)
c = a*b

ValueError: operands could not be broadcast together with shapes (4,3) (3,2) 

In [66]:
a = np.random.randn(12288, 150) # a.shape = (12288, 150)
b = np.random.randn(150, 45) # b.shape = (150, 45)
c = np.dot(a,b)

In [67]:
c.shape

(12288, 45)

In [82]:
a = np.random.rand(3,4)
b = np.random.rand(4,1)

for i in range(3):
  for j in range(4):
    c[i][j] = a[i][j] + b[j]
c

array([[  1.39901805,   1.5086695 ,   1.70320664, ...,   0.63303771,
         -6.99355893,  -5.19175284],
       [  0.85252073,   1.04028396,   1.37206673, ...,  -3.20251753,
         13.46698   , -12.18070896],
       [  1.62427443,   1.13472955,   1.65365361, ...,   7.07509685,
         -3.4168671 ,   2.60315338],
       ..., 
       [ -2.96146223,   2.1500317 ,  10.06477778, ...,   2.61537884,
          6.51774435,  -4.54617819],
       [ -8.23398362,  14.54348309,  12.61102193, ...,  37.95706504,
         17.05921806, -12.72428577],
       [ 11.82529311, -29.29636537,   3.74714481, ...,   6.59741073,
         -0.46133921,   0.71840738]])

In [83]:
c.shape

(12288, 45)

In [84]:
d= a.T+b

In [81]:
d.shape

(4, 3)

In [85]:
a = np.random.randn(2, 3) # a.shape = (2, 3)
b = np.random.randn(2, 1) # b.shape = (2, 1)
c = a + b

In [86]:
c.shape

(2, 3)

In [87]:
a = np.random.randn(4, 3) # a.shape = (4, 3)
b = np.random.randn(3, 2) # b.shape = (3, 2)
c = a*b
c.shape

ValueError: operands could not be broadcast together with shapes (4,3) (3,2) 

In [88]:
a = np.random.randn(12288, 150) # a.shape = (12288, 150)
b = np.random.randn(150, 45) # b.shape = (150, 45)
c = np.dot(a,b)

In [89]:
c.shape

(12288, 45)

In [90]:
a = np.random.randn(3, 3)
b = np.random.randn(3, 1)
c = a*b

In [91]:
c.shape

(3, 3)

In [92]:
a = np.random.randn(2, 3) # a.shape = (2, 3)
b = np.random.randn(2, 1) # b.shape = (2, 1)
c = a + b

In [93]:
c.shape

(2, 3)

In [94]:
a = np.random.randn(4, 3) # a.shape = (4, 3)
b = np.random.randn(3, 2) # b.shape = (3, 2)
c = a*b


ValueError: operands could not be broadcast together with shapes (4,3) (3,2) 

In [95]:
a = np.random.randn(2, 3) # a.shape = (2, 3)
b = np.random.randn(2, 1) # b.shape = (2, 1)
c = a + b
c.shape

(2, 3)

In [96]:
a = np.random.randn(4, 3) # a.shape = (4, 3)
b = np.random.randn(3, 2) # b.shape = (3, 2)
c = a*b

ValueError: operands could not be broadcast together with shapes (4,3) (3,2) 